import { useState } from "react";
import { Modal } from "../../../shared/components/Modal";
import useModal from "../../../shared/components/Modal/useModal";
import { useSelector } from "react-redux";
import { RootState, useCreateStoryMutation } from "../../../shared/store";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { IStory } from "../../../shared/store/slices/UserSlice";
import { toast } from "react-toastify";
import Button from "../../../shared/components/Button";
import { Colors } from "../../../shared/Enums/Stylings";

interface IModalProps {
    isVisible: boolean;
    onClose: () => void;
    level: string | undefined,
    language: string | undefined,
    allStories: IStory[],
    //add other props if needed
}

function GenerateOwnModal({isVisible, onClose, level,language,allStories}: IModalProps){
  const [storyTitle, setStoryTitle] = useState<string>("");
  const user = useSelector((state: RootState) => state.userProfile);
  const [createStory] = useCreateStoryMutation();
  const [generatedTitle, setGeneratedTitle] = useState<string>("");
  const [generatedWords, setGeneratedWords] = useState<{id: 0, word: string, known: number}[]>([]);
  const [generatedStory, setGeneratedStory] = useState<string>();
  const [generatedDescription, setGeneratedDescription] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const apikey = process.env.REACT_APP_GEMINI_API_KEY;



  //AI stuff
  let genAI;
  if (apikey !== undefined) {
    genAI = new GoogleGenerativeAI(apikey);
  }
  const model = genAI?.getGenerativeModel({
    model: "gemini-1.5-flash-8b",
  });

  if(level === undefined || language === undefined){
    language = "english";
    level = "A1"
  }

  //sets 'translationWord' generated by AI
  const generateStory = async () => {
    if(isLoading){
      toast.error("Generowanie danych jest w toku...");
      return;
    }
    let title = "";
    let story = "";
    let description = "";
    let error = false;
    if (model) {
      setIsLoading(true);
      console.log(
        "Czarek właśnie generuje dla Ciebie historie w języku " +
          language +
          " na poziomie " +
          level +
          ":"
      );
      if(storyTitle==""){

        const countResult = await model.countTokens(
          "Generate a compelling and original story title list that captures the essence of a random genre. The title should be between 2-6 words, be memorable, evoke emotion or curiosity, and include at least one strong descriptive word. Consider using elements like alliteration, metaphor, or contrast to make it more engaging. Provide a brief explanation of why this title would appeal to readers of the chosen genre. Titles should be in " +
            level +
            " " +
            language +
            " language. Answer should contain only the titles seperated with comma"
        );

        console.log(countResult.totalTokens);
        if (countResult !== undefined) {
          if (countResult.totalTokens > 850) {
            toast.error("Przekroczono ilość tokenów!");
            return;
          }
        }

      await model
        .generateContent(
          "Generate a compelling and original story title list that captures the essence of a random genre. The title should be between 2-6 words, be memorable, evoke emotion or curiosity, and include at least one strong descriptive word. Consider using elements like alliteration, metaphor, or contrast to make it more engaging. Provide a brief explanation of why this title would appeal to readers of the chosen genre. Titles should be in " +
            level +
            " " +
            language +
            " language. Answer should contain only the titles seperated with comma"
        )
        .then((response) => {
          const responseTitle = response.response;
          title = responseTitle.text().toString();
          let titles = title.split(",");
          console.log(titles);
          title = titles[Math.floor(Math.random() * titles.length)];
          console.log(title);
        })
        .catch((err) => {
          toast.error(
            "Czarek jest obecnie przeciążony. Spróbuj ponownie za chwilę!"
          );
          error = true;
        });


      if (error) return;
    }
    else{

      const countResult = await model.countTokens(
 "translate this title:" + storyTitle + " to "+ language + ". Your answer should contain only the translated title"
      );

      console.log(countResult.totalTokens);
      if (countResult !== undefined) {
        if (countResult.totalTokens > 850) {
          toast.error("Przekroczono ilość tokenów!");
          return;
        }
      }

        await model
        .generateContent(
          "translate this title:" + storyTitle + " to "+ language + ". Your answer should contain only the translated title"
        )
        .then((response) => {
          const responseTitle = response.response;
          title = responseTitle.text().toString();
        })
        .catch((err) => {
          toast.error(
            "Czarek jest obecnie przeciążony. Spróbuj ponownie za chwilę!"
          );
          error = true;
        });
    }
      let arraysOfWords: any = [];

      const countResult = await model.countTokens(
        "generate story in " +
        language +
        " language at " +
        level +
        " level. The story will be about " +
        title
             );
       
             console.log(countResult.totalTokens);
             if (countResult !== undefined) {
               if (countResult.totalTokens > 850) {
                 toast.error("Przekroczono ilość tokenów!");
                 return;
               }
             }

      await model
        .generateContent(
          "generate story in " +
            language +
            " language at " +
            level +
            " level. The story will be about " +
            title
        )
        .then((response) => {
          const responseStory = response.response;
          story = responseStory.text().toString();

          //generate story words
          arraysOfWords = story
            .split(/ |\n/)
            .map((word, index) => {
              if (word !== "") {
                const formattedWord = word.replaceAll("\n", "");

                //Check if you already have a word in folder

                return {
                  id: index,
                  word: formattedWord,
                  known: 0,
                };
              }
            })
            .filter((word) => {
              if (word) {
                return true;
              } else {
                return false;
              }
            });

          // Mapa do przechowywania pierwszego id dla każdego unikalnego tytułu
          const titleToId: any = {};

          // Przetwarzanie obiektów, aby ustawić id na takie samo jak pierwsze wystąpienie tytułu
          arraysOfWords.forEach(
            (object: { id: number; word: string; known: number }) => {
              // Jeśli tytuł jeszcze nie ma przypisanego id, przypisz id z pierwszego wystąpienia
              if (titleToId[object.word] === undefined) {
                titleToId[object.word] = object.id;
              } else {
                // Ustaw id na wartość pierwszego wystąpienia
                object.id = titleToId[object.word];
              }
            }
          );

          console.log(arraysOfWords);
        })
        .catch((err) => {
          toast.error(
            "Czarek jest obecnie przeciążony. Spróbuj ponownie za chwilę!"
          );
          error = true;
        });

      if (error) return;

      const shortStoryCountResult = await model.countTokens(
        "generate very short description, in " +
        language +
        " for this story: " +
        story
             );
       
             console.log(shortStoryCountResult.totalTokens);
             if (shortStoryCountResult !== undefined) {
               if (shortStoryCountResult.totalTokens > 850) {
                 toast.error("Przekroczono ilość tokenów!");
                 return;
               }
             }

      await model
        .generateContent(
          "generate very short description, in " +
            language +
            " for this story: " +
            story
        )
        .then((response) => {
          const responseDescription = response.response;
          description = responseDescription.text().toString();
          console.log(description);
        })
        .catch((err) => {
          toast.error(
            "Czarek jest obecnie przeciążony. Spróbuj ponownie za chwilę!"
          );
          error = true;
        });

      if (error) return;
      setGeneratedTitle(title);
      setGeneratedStory(story);
      setGeneratedWords(arraysOfWords);
      setGeneratedDescription(description);
      setIsLoading(false);
      setStoryTitle("");
    }
  };

  //On story create
  const onCreateStory = async (newStory: IStory) => {
    return await createStory({ newStory: newStory, userID: user.value })
      .unwrap()
      .then(() => {
        toast.success("Pomyślnie utworzono historie!");
      })
      .catch(() => {
        toast.error("Błąd podczas tworzenia historii!");
      });
  };

  return (
<Modal isVisible={isVisible} onClose={onClose}>
  <div className="absolute bg-white rounded-lg shadow-xl mt-20 z-20 h-auto w-11/12 top-0 xl:w-1/3 xl:left-1/2 xl:transform xl:-translate-x-1/2 xl:mt-10">
    <div className="flex flex-col p-6 h-full w-full overflow-y-auto scrollbar-hide">
      <h2 className="font-inter font-bold text-3xl text-fifth text-center mb-6">
        Generuj własną historię
      </h2>

      <div className="flex flex-col gap-4 font-inter">
        {generatedDescription === "" ? (
          isLoading ? (
            <div className="flex justify-center items-center text-lg text-gray-600">
              Ładowanie...
            </div>
          ) : (
            <div className="flex flex-col gap-6">
              <div className="text-center">
                <p className="text-lg font-semibold">Wpisz tytuł Twojej historii:</p>
                <p className="text-sm text-gray-500 mt-1">
                  Tytuł może być wpisany w dowolnym języku. Przetłumaczymy go dla Ciebie.
                </p>
              </div>
              <input
                type="text"
                placeholder="np. Marta kocha tortille"
                className="w-full bg-secondarylight rounded-lg border border-main p-2 focus:ring-2 focus:ring-main focus:outline-none"
                value={storyTitle}
                onChange={(e: any) => {
                  setStoryTitle(e.target.value);
                }}
              />
              <Button
                onClick={generateStory}
                bgColor={Colors.SECONDARY}
                className="w-full py-2 rounded-lg text-white font-medium shadow hover:shadow-lg hover:bg-opacity-90 transition duration-200"
              >
                Wygeneruj własną historię
              </Button>
            </div>
          )
        ) : (
          isLoading ? (
            <div className="flex justify-center items-center text-lg text-gray-600">
              Ładowanie...
            </div>
          ) : (
            <div className="flex flex-col gap-4">
              <h3 className="text-xl font-semibold text-main">Podgląd:</h3>
              <p className="text-gray-700">
                <span className="font-semibold">Tytuł:</span> {generatedTitle}
              </p>
              <p className="text-gray-700">
                <span className="font-semibold">Opis:</span> {generatedDescription}
              </p>
              <p className="text-gray-700">
                <span className="font-semibold">Poziom:</span> {level || "A1"},{" "}
                <span className="font-semibold">Język:</span> {language || "English"}
              </p>
              <input
                type="text"
                placeholder="Wprowadź tu nowy tytuł..."
                className="w-full bg-secondarylight rounded-lg border border-main p-2 focus:ring-2 focus:ring-main focus:outline-none"
                value={storyTitle}
                onChange={(e: any) => {
                  setStoryTitle(e.target.value);
                }}
              />
              <Button
                onClick={generateStory}
                bgColor={Colors.SECONDARY}
                className="w-full py-2 rounded-lg text-white font-medium shadow hover:shadow-lg hover:bg-opacity-90 transition duration-200"
              >
                
                Wygeneruj ponownie
              </Button>
              <Button
                onClick={() => {
                  let newID = 0;
                  if (allStories.length > 0) {
                    newID = allStories[allStories.length - 1].id + 1;
                  }
                  if (level === undefined || language === undefined) {
                    language = "english";
                    level = "A1";
                  }
                  onCreateStory({
                    id: newID,
                    description: generatedDescription,
                    language: language,
                    level: level,
                    title: generatedTitle,
                    words: generatedWords,
                    wordAmount: 0,
                    wordKnownAmount: 0,
                  });
                  setGeneratedDescription("");
                  setGeneratedStory("");
                  setGeneratedTitle("");
                  onClose();
                }}
                bgColor={Colors.SECONDARY}
                className="w-full py-2 rounded-lg text-white font-medium shadow hover:shadow-lg hover:bg-opacity-90 transition duration-200"
              >
                Dodaj do kolekcji
              </Button>
            </div>
          )
        )}
      </div>
    </div>
  </div>
</Modal>
  );
}

export default GenerateOwnModal;